// SPDX-License-Identifier: MIT
// Autogenerated by build.rs - do not edit directly.

pub const SIMH_GIT_HASH: &str = "928bc54+uncommitted";
pub const _SIMH_GIT_TIMESTAMP: &str = "2026-01-20 21:44:53-08:00";
pub const SIMH_VERSION_MAJOR: u32 = 0;
pub const SIMH_VERSION_MINOR: u32 = 1;
pub const SIMH_VERSION_PATCH: u32 = 0;
pub const SIMH_VERSION_MODE: &str = "Development";
        